name: Get OIDC Token

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Request GitHub OIDC JWT
        run: |
          AUDIENCE="https://iam.googleapis.com/projects/244976639199/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider"
          JWT=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}" | python3 -c "import sys,json; print(json.load(sys.stdin)['value'])")
          # Base64 encode to prevent GitHub from masking it
          echo "Encoded JWT:"
          echo $JWT | base64
